### ISSUE TITLE
Working with ngResource services?

### ISSUE THREAD

**Issue by rvillars** [guylabs/angular-spring-data-rest#1]
Your projects seems promising but I have some difficulties with the documentation. You write:

> Now you are able to instantiate the SpringDataRestAdapter object and process a given response:
>```javascript
> var processedResponse = new SpringDataRestAdapter(response);
>```

What is the 'response'? Do I have to get it "manually" with $http? What about ngResource that is used by angular-spring-data-rest itself?

Normally with ngResource you can create and use a resource service like this:
```javascript
myApp.factory('Category', function ($resource) {
    return $resource('category/:categoryId', {categoryId: '@id'});
}

$scope.categories = Category.query(); // in the controller
```

How can I use angular-spring-data-rest this way to also make use of all ngResource convenience functions like 'get' or 'save'?

**Comment by rvillars** [comment]
The new promise function is very helpful. And also your example project (https://github.com/guylabs/angular-spring-data-rest-sample) was a helpful starting point. Thx! I was now able to adapt the framework for my project (going to check in the code soon).

If someone is interested in using angular-spring-data-rest with a active record pattern approach, there is a quite interesting example at http://g00glen00b.be/spring-data-angular.

**Comment by guylabs** [comment]
Nice! And a very interesting approach in the blog post. Thanks for sharing it.

**Comment by ziftytodd** [comment]
I have to agree with Roger, the documentation is great on what to do ONCE you have a response to process. But it's totally unclear (at first) how you're supposed to get that response. I think most people are coming to this project from https://github.com/jmarquis/angular-hateoas where you can just drop it in and it enhances the functionality of the $resource, whereas this project doesn't appear to do that at all. 

From what I can gather, from the sample project in rvillars comment (which was very helpful), you have to pretty much write your own custom resource, which seems overkill if you're using the standard spring data rest repository to expose an API. Not sure why implementing the same functionality of $resource, with ability to override, wouldn't make sense. It would cut out a lot of boilerplate for simple collections.

At the very least, please consider adding more documentation to this project showing the full code for the basic CRUD operations, including making the request, or linking to the sample project.

Also, the documentation refers to SpringDataRestAdapter.processWithPromise(promise), but that appears to not be a valid method name and it works just fine with just SpringDataRestAdapter.process(promise).

**Comment by guylabs** [comment]
Hi @ziftytodd,

thanks for your opinion and I try to add more documentation about how to get the response. The link to the sample project is already there: https://github.com/guylabs/angular-spring-data-rest#see-how-it-works (even before the TOC ;))

And thanks for spotting the issue with the `processWithPromise` method. I will fix it asap.

Thanks and regards,

Guy
