### ISSUE TITLE
Given data is not of type object.

### ISSUE THREAD

**Issue by mlegnani** [guylabs/angular-spring-data-rest#10]
I'm experiencing problems when processing spring data rest responses like:
```json
{
  "_embedded" : {
    "timeSeries" : [ {
      "id" : 1400,
      "lastDate" : "1991-01-06T23:00:00.000+0000",
      "data" : [ 89.34576078, 90.86743282, 91.5561206, 91.52988487 ],
      "tsDataType" : "CLOSE",
      "_embedded" : {
        "asset" : {
          "id" : 15,
          "ticker" : "BUHY:IND",
          "description" : "Bloomberg USD High Yield Corporate Bond Index",
          "provider" : "BLOOMBERG",
          "assetClass" : "INDEX",
          "indexType" : "BOND",
          "assetClassForType" : "INDEX"
        }
      },
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/alphaquant-web/restdata/timeSeries/1400"
        }
      }
    }, {
      "id" : 52,
      "lastDate" : "2015-05-31T22:00:00.000+0000",
      "data" : [ 156.931961, 157.007523, 156.968109, 157.001785, 156.967865, 100.0 ],
      "tsDataType" : "OPEN",
      "_embedded" : {
        "asset" : {
          "id" : 15,
          "ticker" : "BUHY:IND",
          "description" : "Bloomberg USD High Yield Corporate Bond Index",
          "provider" : "BLOOMBERG",
          "assetClass" : "INDEX",
          "indexType" : "BOND",
          "assetClassForType" : "INDEX"
        }
      },
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/alphaquant-web/restdata/timeSeries/52"
        }
      }
    } ]
  }
}
```
I get this exception
"Given data '15' is not of type object."
when processing the response with SpringDataRestAdapter.process()

**Comment by guylabs** [comment]
Hi,

could you maybe provide the way how you call the `SpringDataRestAdapter` with all the parameters? Then I will try to reproduce it.

Thanks and regards,

Guy

**Comment by mlegnani** [comment]
Hi Guy,
I have a service 
                   getTsList : function() {
			var urlToCall = relativeUrl('/restdata/assets/15/tsList');
			var httpPromise = $http.get(urlToCall).success(function (response) {
		            self.response = angular.toJson(response, true);
		    });
		    return SpringDataRestAdapter.process(httpPromise);
		}
and then I call it in my controller:
self.reloadAssets = function(){
	    assetManagementService.getTsList().then(
	        function (processedResponse) {
		        self.tsList = processedResponse._embeddedItems;
		    },
		    function(errResponse) {
                        console.error('Error retrieving list from server');
		}
	    );
	};	

Please note that this code works perfectly when applied to other services.

Thanks a lot,
Massimo

**Comment by guylabs** [comment]
Hi Massimo,

in my sample app https://github.com/guylabs/angular-spring-data-rest-sample/blob/master/src/main/webapp/js/app.js#L32 I use the exact same code and there it works. Looks like it's something with the data as the exception says something about `15` and you have ids that have this value. I will create a test with your response data and hopefully I am able to reproduce it.

I also updated your comments to use the code blocks such that the code is more readable.

Thanks and regards,

Guy

**Comment by mlegnani** [comment]
Thanks Guy, I tried to debug your code and I suppose the problem is that the id of the embedded asset object is treated like an embeded object and not ike a value.
Thanks,
Massimo

**Comment by guylabs** [comment]
Hi Massimo,

sorry for my late reply but I was on vacations and lately I hadn't the time to look into it. But I found the issue and fixed it right away. Can you please try it with the master and come back to me when it works?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Massimo,

I will close the issue due to inactiviti. You can reopen it if it doesn't work for you.

Thanks and regards,

Guy
