### ISSUE TITLE
Would it be possible to provide the lib through a cdn?

### ISSUE THREAD

**Issue by hostirosti** [guylabs/angular-spring-data-rest#16]
Hi Guy,

great angular module! Do you consider to provide it through a CDN (jsdelvr or cdnjs or ...)?

Cheers,
Robert

**Comment by guylabs** [comment]
Hi Robert,

thanks for the praise ;). Till now I haven't got this plan but I can have a look at it and add it to a CDN. Do you have a favorite/preferred CDN?

Thanks and sorry for the late response,

Guy

**Comment by hostirosti** [comment]
Hi Guy,

both cdn's jsdelvr and cdnjs are free and libs can be contributed through pull requests. jsdelvr seems to be a bit more straight forward to me to add a library.

Cheers,
Robert

**Comment by kamronbatman** [comment]
https://cdn.rawgit.com/guylabs/angular-spring-data-rest/master/dist/angular-spring-data-rest.min.js

**Comment by guylabs** [comment]
Hi Kamron,

thanks a lot for the link! 

@hostirosti Would that be enough for you? Can I then close the issue?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Closed due to inactivity.
