### ISSUE TITLE
Allow AngularJS dependency version 1.4

### ISSUE THREAD

**Issue by georgwittberger** [guylabs/angular-spring-data-rest#18]
Your `bower.json` requires AngularJS to be version `~1.3.15` which means any **patch level greater than 1.3.15** but definitely a version **less than 1.4**. In my current project I would like to use the most recent AngularJS version 1.4.8 together with your module. The only way to make it work is to provide a custom resolution in my `bower.json` which forces Bower to use version 1.4.8. This is a dirty workaround and produces warning during the build process.
I have already tested your module in conjunction with AngularJS 1.4.8 and it seems to work fine for my use cases. Therefore, could you please update your `bower.json` to allow the recent version?

For example you could use the caret prefix instead: `^1.3.15` - This allows any minor version greater than 1.3.15 and less than 2.0, see https://github.com/npm/node-semver#caret-ranges-123-025-004

**Comment by guylabs** [comment]
Hi Georg,

sorry for my late response but I didn't have the time to do it earlier. I just released `0.4.4` of the module which uses Angular `1.4.8`. So you just need to update to `0.4.4` and then you can use it the proper way.

I will close the issue now. If you have anything else please comment it here or reopen the issue.

Happy christmas! :)

Regards,

Guy
