### ISSUE TITLE
Support Angular 1.5

### ISSUE THREAD

**Issue by rkusuma** [guylabs/angular-spring-data-rest#21]
Hi @guylabs ,

Can you make this support for angular `1.5.x` ?

Thank You

**Comment by guylabs** [comment]
Hi @rkusuma,

did you already test it with `1.5.x`? If yes what were the issues? Currently I do not have that much time but if you already had a look at it then your findings would help fixing it quicker. The best would be if you could create a PR with the working version of the module with Angular `1.5.x`.

Till now I didn't test it with the `1.5.x` version.

Thanks and regards,

Guy

**Comment by torsten-sauer** [comment]
I created PR #26 with updated bower.json

**Comment by guylabs** [comment]
Hi @rkusuma,

thanks to the pull request #26 of @torsten-sauer we now have Angular 1.5 support. You can update to the master version to use it.

Thanks and regards,

Guy

**Comment by rkusuma** [comment]
@guylabs thanks for your info.. and thanks @torsten-sauer for the PR

**Comment by rkusuma** [comment]
@guylabs you are not planning tag to version `0.4.5` ?

**Comment by guylabs** [comment]
Hi @rkusuma,

I think I will first add the flag mentioned in #23 and then do a new release.

Thanks and regards,

Guy
