### ISSUE TITLE
Correct use of resources children

### ISSUE THREAD

**Issue by markgargan** [guylabs/angular-spring-data-rest#22]
Hey Guy,

      Could I ask you a question if you have time? Sorry I realise this should have been an issue in it's own right. 

<img width="919" alt="screen shot 2016-03-17 at 21 02 07" src="https://cloud.githubusercontent.com/assets/1690750/13862169/632b9bbe-ec89-11e5-8168-1d9b6d1e02ed.png">

I'm using SpringDataRestAdapter to interact with my spring data rest api. From the screen shot you can see that I've just loaded all the questions and I'm attempting to load their answers (one-to-many) relationship. In the debug window the _embeddedItems array is an array of Questions with _links to each questions answers. I'm trying to prompt SpringDataRestAdapter to autoload the answers by passing 'answers' as an argument to the processWithPromise call but to no avail.

The urls look like http://localhost:8080/api/questions http://localhost:8080/api/question/1/answers

The Question.loadAnswers(question) call is commented out... It works in that it loads the question's answers but I felt I was using the framework incorrectly.

Here is the method

```
Question.loadAnswers = function (question) {

            question.answers = question.answers? question.answers : [];

            angular.forEach(question._links.answers, function (answerLink) {
                var deferred = $http.get(answerLink);
                return SpringDataRestAdapter.processWithPromise(deferred).then(function (data) {
                    question.answers = data._embeddedItems;
                });
            });
        };
```

Congratulations on an excellent piece of coding Guy! I've also posted this question up on stackoverflow in case the issue is with my understanding of promises as opposed to how to use the framework :)

http://stackoverflow.com/questions/36072090/springdatarestadapter-load-child-resources

Thanks, Mark.

**Comment by guylabs** [comment]
Hi Mark,

sorry from my late response and thanks a lot for the praise :). You need to set the `recursive` flag on the `fetch` function such that the following call will fetch the `answers` properly:

```javascript
SpringDataRestAdapter.process(deferred, 'answers', true).then(...)
```

You can see the documentation here https://github.com/guylabs/angular-spring-data-rest#the-fetch-method-parameters and here you can see a running example https://github.com/guylabs/angular-spring-data-rest/blob/master/test/angular-spring-data-rest-provider.fetch.spec.js#L148

I hope this solves your issue.

Thanks and regards,

Guy

**Comment by markgargan** [comment]
Yer a gentleman Guy,

           Thanks for getting back to me, aye I found that in the docs at
some stage. Thanks for the framework, it's made my life a helluva lot
easier!

Thanks,
Mark.

**Comment by guylabs** [comment]
Hey Mark,

ok cool that you found out yourself and thanks for using it! :)

Regards,

Guy
