### ISSUE TITLE
Collection of Links

### ISSUE THREAD

**Issue by robopeter** [guylabs/angular-spring-data-rest#24]
I have some HAL+JSON data which looks like: 

```
{
  "_embedded": {},
  "_links": {
    "self": {
      "href": "http://localhost/api/article"
    },
    "api/article": [
      {
        "href": "/api/article/1"
      },
      {
        "href": "/api/article/2"
      },
      {
        "href": "/api/article/3"
      },
      {
        "href": "/api/article/4"
      }
    ]
  }
}
````

Notice that the "api/article" key in "_links" has an array of objects.  This is similar to the "admins" link on the HAL specification page: http://stateless.co/hal_specification.html

When I try to use the following bit of code: 

```
SpringDataRestAdapter.process($http.get('/api/article'), 'api/article').then(function(processedResponse) {
    console.log(processedResponse);
});
```

I get the following exception: 

```
angular.js:13550` Error: The provided resource name 'api/article' has no valid URL in the 'href' property.
    at checkUrl (angular-spring-data-rest.js:507)
    at getProcessedUrl (angular-spring-data-rest.js:349)
    at angular-spring-data-rest.js:281
    at Object.forEach (angular.js:336)
    at angular-spring-data-rest.js:267
    at processQueue (angular.js:15961)
    at angular.js:15977
    at Scope.$eval (angular.js:17229)
    at Scope.$digest (angular.js:17045)
    at Scope.$apply (angular.js:17337)
```

Doing a quick bit of looking through the code... it looks like perhaps an array of links for the same key is not supported? Is this the case or am I doing something else wrong? I was expecting "processedResponse" to be an array of promises. How would you handle a collection of links?

**Comment by guylabs** [comment]
Hi @robopeter,

yes this is indeed not supported as such kind of responses are not generated by the Spring Data Rest back end as far as I know. What kind of back end do you use to create the responses?

But another question: Why don't you use the embedded items for the links list? Or what is the added value of using multiple links in a single link resource? In the example you provided it just iterates over the admin resources. A use case form your side would help to understand it and try to search for a valid solution.

Currently I do not have much time and maybe you could come up with a pull request and then we can discuss it again.

Thanks for pointing it out and regards,

Guy

**Comment by guylabs** [comment]
Hi,

I will close the issue due to inactiviti. If you have anything to add please add a comment or reopen the issue.

Thanks and regards,

Guy
