### ISSUE TITLE
Fetching resources compatible with saving

### ISSUE THREAD

**Issue by domgom** [guylabs/angular-spring-data-rest#25]
Hi,
I have a manyToOne relation between Type and Channel entities. When I prefetch the type and channels type.channel gets the embedded object inside. This is a problem when I try to save the resource because in order to work spring data rest is expecting type.channel to be an URL.
Is any possibility of saving resources work properly with prefetched children?
Thanks in advance.

**Comment by guylabs** [comment]
Hi @domgom,

well the `angular-spring-data-rest` module is used to easily read the responses from a Spring Data REST back end. For this it adds additional data to the response such that you can easily iterate over it in the front end.

When you want to save an object you would need to remove all these additional fields such that you have the original response again and then you are able to save this object.

Maybe we could provide a method which removes the extra data fields and "resets" the response to the initial value such that you can adapt it and then save it. 

As I do not have much time for it maybe you could create a pull request with a first draft.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @domgom,

any news on this? If not then I will close the issue and you can always reopen it if there is something more.

Thanks and regards,

Guy
