### ISSUE TITLE
Inheritance support

### ISSUE THREAD

**Issue by bergacat1** [guylabs/angular-spring-data-rest#27]
Hi,

When we have a class "A" with two subclasses "B" and "C", we could have a spring data rest repository for the class "A" which would return all "B" and "C" objects in the following format:
```
{
 "_embedded": {
    "as": [ "A" class objects ],
    "bs": [ "B" class objects ]
  },
  "_links": { ... },
    "profile": { ... },
    "search": { ... }
  },
  "page": { ... }
}
```

Would it be possible to know which is the class of each embedded object?

Thank you.``

**Comment by guylabs** [comment]
Hi @bergacat1,

sorry for my delay but I was on a longer trip and now I am working partially.

Well if you do not have any property in the JSON which identifies the class `B` or `C` then not as in the JSON you cannot get the inheritance information of the Java classes.

You could just add an identifier to the class `A` which then would be different in class `B` or class `C`.

Does that answer your question?

Thanks and regards,

Guy

**Comment by bergacat1** [comment]
But you can determine which is the class of every object in the JSON. In the previous example you can see the name "as" associated with the list of objects of class A, and the name "bs" associated with the list of objects of class B. If there were another class called "OtherClass", the name for the list of objects of this type would be "otherClasss".

**Comment by bergacat1** [comment]
Related to this issue, I'm experimenting a problem which makes impossible to keep working with this module. I will explain the full use case so you can reproduce the problem.

I have a class "User" related with some "ExternalUsers":

```
public class User {
  ...
  @OneToMany(...)
  private List<ExternalUser> externalUsers;
  ...
}
```
The class "ExternalUser" is the super-class of "YouTubeChannel" and "GoogleUser", so the list of ExternalUsers in the User class can contain different types of objects.

The problem occurs when I use the `user._resources('externalUsers').get()` to obtain the list of ExternalUsers related with a user. The returning object only contains one ExternalUser object but the raw response from the server is the following:

```
{
  "_embedded" : {
    "googleUsers" : [ {
      "name" : "Albert Berga",
      "url" : "https://plus.google.com/107051416216090286883",
      "_links" : {
        "self" : {
          "href" : "http://10.50.54.194:8080/googleUsers/107051416216090286883"
        },
        "googleUser" : {
          "href" : "http://10.50.54.194:8080/googleUsers/107051416216090286883"
        },
        "youTubeChannels" : {
          "href" : "http://10.50.54.194:8080/googleUsers/107051416216090286883/youTubeChannels"
        },
        "User" : {
          "href" : "http://10.50.54.194:8080/googleUsers/107051416216090286883/User"
        }
      }
    } ],
    "youTubeChannels" : [ {
      "id" : "UCXKrFkh0t1KvtQJdg9NwTuQ",
      "name" : "Albert Berga",
      "url" : "http://www.youtube.com/channel/UCXKrFkh0t1KvtQJdg9NwTuQ",
      "_links" : {
        "self" : {
          "href" : "http://10.50.54.194:8080/youTubeChannels/UCXKrFkh0t1KvtQJdg9NwTuQ"
        },
        "youTubeChannel" : {
          "href" : "http://10.50.54.194:8080/youTubeChannels/UCXKrFkh0t1KvtQJdg9NwTuQ"
        },
        "googleUser" : {
          "href" : "http://10.50.54.194:8080/youTubeChannels/UCXKrFkh0t1KvtQJdg9NwTuQ/googleUser"
        },
        "User" : {
          "href" : "http://10.50.54.194:8080/youTubeChannels/UCXKrFkh0t1KvtQJdg9NwTuQ/User"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "http://10.50.54.194:8080/Users/68c54696-7fee-4082-9bce-86e1904ca925/externalUsers"
    }
  }
}
```
The YouTubeChannel object in the raw response is inaccessible using the angular-spring-data-rest module.

Thank you,

Albert

**Comment by bergacat1** [comment]
I've just seen in the documentation that there is a configuration ("embeddedNamedResources") which prevents this behaviour. So it was my problem of don't look at the documentation. 

Sorry for the disturbances.

**Comment by guylabs** [comment]
Hi @bergacat1 

ok so everything is solved and you could address your problem yourself? I will close the issue for now and if there is anything else please reopen it.

Thanks and regards,

Guy
