### ISSUE TITLE
Draft a new release for 1.5 support

### ISSUE THREAD

**Issue by janpapenbrock** [guylabs/angular-spring-data-rest#28]
Would that be possible? Thanks.

**Comment by guylabs** [comment]
Hi,

sorry for my delay but I was on a longer trip and now I am working partially.

Yes when I release `0.4.5` then there is Angular `1.5` support integrated. You can always use the master if you want to to have that in. I just do not know when exactly I am able to do it.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @janpapenbrock 

just released `0.4.5` with the Angular 1.5 support.

Sorry for the delay.

Regards,

Guy
