### ISSUE TITLE
POST with Spring projections?

### ISSUE THREAD

**Issue by Busata** [guylabs/angular-spring-data-rest#29]
Hi, 

I have a collection of items, for which I have a projection setup in Spring boot, so that it inlines some data that I don't want to fetch for each item individually.

I'm doing the save with the following code:

`this.clusterResponse._resources('self').save({
        name: cluster.name,
        analysisMethods: cluster.analysisMethods.map((method) => method._links.self)
      }`,

but this returns me a resource with links, not taking into account the projection (since you need to add this explicitly by adding ?projection=name.

The only thing I want is to create a new cluster in this case, and add the item to the list, so I don't need to refresh the entire list or refetch the invidual item. Any examples on how to do this?

**Comment by guylabs** [comment]
Hi @Busata 

projections were never tested with this library but I think you will need to execute the save request by your own by getting the URL from the response, then add the parameter for the projection and add the body. So you cannot use the predefined `$resource` which you receive from the `_resources('self')` call.

Would this work in your case?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @Busata 

I did not get an answer from you so I will close the issue now due to inactivity but you can always reopen it.

Thanks and regards,

Guy
