### ISSUE TITLE
Automatically retrieve links in an object property

### ISSUE THREAD

**Issue by morious** [guylabs/angular-spring-data-rest#32]
Is there a way to automatically retrieve links in a payload that looks like the below?

```
personprojectsesByPersonid: [ ],
personskillsesByPersonid: [
    {
        _links: {
            skillsBySkillid: {
                href: "http://localhost:8985/api/skills/1"
            },
            personByPersonid: {
                href: "http://localhost:8985/api/people/4"
            }
        }
    },
    {
        _links: {
            skillsBySkillid: {
                href: "http://localhost:8985/api/skills/2"
            },
            personByPersonid: {
                href: "http://localhost:8985/api/people/4"
            }
        }
    }
],
```

**Comment by guylabs** [comment]
Hi @morious 

well it would be possible if you change the implementation but out of the box it is not possible to parse this kind of response. The module was created for a Spring Data REST back end. You can configure it with these properties https://github.com/guylabs/angular-spring-data-rest#configuration-of-the-springdatarestadapter but this is all what you can configure. 

If possible you can change the response to fit the format or create a fork which works with this response.

Thanks and regards,

Guy
