### ISSUE TITLE
Relative _links

### ISSUE THREAD

**Issue by EgidioCaprino** [guylabs/angular-spring-data-rest#5]
Hello.

I would like to try out this Angular plugin, but in my Spring Data Rest responses, all the _link contains the servlet context path. My application is under an HTTP server, so URL with a context path are all remapped to a wrong URL.

This is an example GET respnose on http://localhost/rest/measure

```

{
  "_links" : {
    "self" : {
      "href" : "http://localhost/raspberry-grow-room/rest/measure{?page,size,sort}",
      "templated" : true
    }
  },
  "_embedded" : {
    "measure" : [ {
      "unit" : "Â°C",
      "iconClass" : "fa fa-fire",
      "_links" : {
        "self" : {
          "href" : "http://localhost/raspberry-grow-room/rest/measure/1"
        },
        "locales" : {
          "href" : "http://localhost/raspberry-grow-room/rest/measure/1/locales"
        }
      }
    } ]
  },
  "page" : {
    "size" : 20,
    "totalElements" : 1,
    "totalPages" : 1,
    "number" : 0
  }
}
```

Can you see the problem? I want to remove the /raspberry-grow-room base path. Can you please help me?

Egidio

**Comment by guylabs** [comment]
Hi Egidio,

you are able to set the base URL on the `org.springframework.data.rest.core.config.RepositoryRestConfiguration` class in your Java servlet configuration. Here is an example of it:

```java
@Configuration
public class WebConfiguration extends RepositoryRestMvcConfiguration {

    @Override
    protected void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
        try {
            config.setBaseUri(new URI("http://localhost"));
        } catch (URISyntaxException exception) {
            throw new RuntimeException("Cannot set base URI", exception);
        }
    }

}
```

The other option would be to deploy the WAR file to the `ROOT` of Tomcat (or any other servlet container) such that your context is not used anymore.

The last option is to configure an Apache HTTP server in front of your Tomcat and use a proxy configuration wich hides the context from the outside.

I hope this helps you.

Regards,

Guy

**Comment by EgidioCaprino** [comment]
Hi,

Unfortunately it does not work. I still have the context root in the paths.

Here is my code:

```
package com.raspberrygrowroom.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.data.rest.core.config.RepositoryRestConfiguration;
import org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration;

import java.net.URI;
import java.net.URISyntaxException;

@Configuration
public class RestConfig extends RepositoryRestMvcConfiguration {

  @Override
  protected void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
    try {
      config.setBaseUri(new URI("http://localhost"));
    } catch (URISyntaxException e) {
      throw new RuntimeException(e);
    }
  }

}
```

**Comment by guylabs** [comment]
Hi Egidio,

did you try the solution with the `ROOT` WAR deploy to your servlet container? And is your `RestConfig` the only  `RepositoryRestMvcConfiguration` in your classpath?

For the `ROOT` war you can check a how to here: http://macgyverdev.blogspot.ch/2014/02/how-to-change-context-root-to-in-tomcat.html

Hope this helps.

Regards,

Guy

**Comment by EgidioCaprino** [comment]
Hello,

It seems the only way to deploy my application under the root context. Now I get the paths in the right way.

Thank you very much.

Egidio

**Comment by guylabs** [comment]
Hi Egidio,

ok nice. I'm glad that I could help you out!

Thanks for closing it and have a nice weekend,

Cheers,

Guy
