### ISSUE TITLE
Problem with automatically fetching

### ISSUE THREAD

**Issue by sveba** [guylabs/angular-spring-data-rest#6]
Hi Guy,

first of all I want to thank You for Your great work. I'm trying to use the fetch feature of the module and it didn't work for me at all. The resolvedResponse is always the same as before. I'm using v0.3.1

Than I tried the https://github.com/guylabs/angular-spring-data-rest-sample. The sample about automatic link fetching delivered a lot of 404s in the chromes console.

I have created a fork for the example with working parent structure and a pull request in the angular-spring-data-rest-sample repository so You can verify my problem.

I have also looked at the js-code and I'm almost sure that the problem is in the fetch function and the usage of the $http without resolving the promise.

Hope this can help You.

BR,
Shari

**Comment by guylabs** [comment]
Hi Shari,

thanks for the pull request and for reporting the issue. I'll have a look at the beginning of next week as I now do not have the time for that. I hope this is ok for you.

I'll come back to you as soon as I have found the issue.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Shari,

well the problem about the `404`'s is that the categories doesn't have any parent, so the link to the parent returns a `404` and that is as Spring Data REST defines it.

I also checked out your branch and ran it, but there I don't see any issue in the sample project. Can you please elaborate more on this? And what do you mean that the "resolvedResponse" is always the same? Which response do you mean? The one from the fetch function or the one from the main request?

And about the statement that the promise isn't resolved: do you mean the `success` function is not called properly or is not good?

Regards,

Guy

**Comment by sveba** [comment]
Hi Guy,

the problem with the example is, that it doesn't prove that the automatic link fetching is working, because the parents are not being found (404s) and therefor the $scope.categories can not be extended with the parent data. 

resolvedResponse is the returned data in file automatic-link-fetching.html, line 27-28. So I would say the response of the main request ( SpringDataRestAdapter.processWithPromise )

"Not resolved promise" was maybe not the right expression :) What I mean is that:
processDataWithPromise is being resolved without waiting/resolving the result of the $http promise called in the fetch function. Let me try to write down the call stack:
1. processWithPromise
2. processData
3. fetchFunktion
4. $http makes the get 
5. fetchFunktion returns
6. processData returns data (the $http.get is not ready yet!)
7. processWithPromise resolves the data returned from the processData (without the information that should be fetched)
8. $http.get is ready, but too late because the processWithPromise has already returned/resolved the data to the caller

You can easily prove that by setting breakpoints in lines:
93  "data[key] = recursive ? processData(responseData, ..."
and 303 "deferred.resolve(processedData);"

of the angular-spring-data-rest-provider.js 

Regards,
Shari

**Comment by guylabs** [comment]
Hi Shari,

ok now I see your problem. Ok I'll need to rewrite some things such that the caller gets the proper resolved response. Thanks for catching this issue! I'll work on it as soon as possible and provide a new release which fixes this issue.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Shari,

I just committed the changes needed to the master branch. The sample now works with your pull request. You just need to exchange the `processWithPromise` function with the `process` function as now the `SpringDataRestAdapter` has just the `process` method which is able to handle promises and returns promises.

Can you please verify the functionality? I still need to add some more tests and update the documentation, but when everything is working as you need it, I will release a new version of it.

Thanks a lot and regards,

Guy

**Comment by sveba** [comment]
Nice work. I can confirm that the fork is working with this version. I can check tomorrow on a bigger project if everything is OK.

Thanks again for the quick fixing :+1: 

As I can see, that caused a bigger refactoring :)

**Comment by guylabs** [comment]
Thanks and I'm glad I could help. Now the whole promises are much more cleaner and it's done the right way ;). Ok just come back here when you tested it and then I can do a new release.

And yes that was a bigger refactoring ;)

**Comment by guylabs** [comment]
I changed some more things again including the tests and some other things. It should still work as expected. But can you test it once again if you don't mind?

**Comment by sveba** [comment]
sure. No problem. But tomorrow. I'm done for today :)

**Comment by sveba** [comment]
My tests went fine.

Thanx again!

**Comment by guylabs** [comment]
Hi Shari,

I just released [`0.4.0`](https://github.com/guylabs/angular-spring-data-rest/releases/tag/0.4.0) with the changes you tested. I hope now everything runs as expected.

Thanks again for finding the issue.

Regards,

Guy
