### ISSUE TITLE
Automatic fetched data is not being processed

### ISSUE THREAD

**Issue by sveba** [guylabs/angular-spring-data-rest#8]
Hi Guy,

I have another one :)

After automatic fetching data there is the usual "_embedded" attribute in it and not the "_embeddedItems" attribute.

I researched a little bit in the code and found out that the fetched data is actually not being processed. This is change, which fixes this issue.
Line 107:
```javascript
if (recursive) {
   return processData(responseData.data, fetchLinkNames, true).then(function (processedData) {
        data[key] = processedData;
   });
} else {
    return processData(responseData.data).then(function (processedData) {
       data[key] = processedData;
    });
}
```

**Comment by guylabs** [comment]
Hi Shari,

I just checked in the fix and a test for it. Could you maybe test it and tell me if it worked such that I can close the issue?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi Shari,

did you have the time to test it? I want to release the 0.4.1 on the weekend.

Thanks and regards,

Guy
