### ISSUE TITLE
URL templates

### ISSUE THREAD

**Issue by aycanadal** [guylabs/angular-spring-data-rest#9]
SDR by default produces urls with templates similar to:
http://localhost:8080/api/users/0
Is it possible to get a $resource function with such template from a processed resource? So that  api._resources('users') would return equivalent of $resource('/api/users/:userId'). Is this feature currently available?

**Comment by guylabs** [comment]
Hi,

currently this is not supported but I could add something like the following:

If you want to have a URL template parameter in the `$resource` object, then you could call it the following way:

```javascript
processedResponse._resources("categories/:categoryId")
```

And then I would split the resources name by the `/` and get the URL from the resource and add the `:categoryId` as a suffix to the URL returned in the `$resources` object. This is the only way I currently see.

What do you think about that?

Thanks and regards,

Guy

**Comment by aycanadal** [comment]
I think it would work just fine.

**Comment by guylabs** [comment]
Hi,

could you please try the new feature with the master and tell me if it works as you need it? Please also check the documentation where I added it too -> https://github.com/guylabs/angular-spring-data-rest#the-_resources-method-parameters-and-return-type

If it works I will release 0.4.2.

Thanks and regards,

Guy

**Comment by aycanadal** [comment]
Just checked them both. Working good. Thanks.

**Comment by guylabs** [comment]
Ok just released 0.4.2. Thanks and regards,

Guy
